### ISSUE TITLE
Pagination and Search Results

### ISSUE THREAD

**Issue by martaotto** [akvo/unep-gpml#273]
Remove pagination from the top. Ability to sort ascending and descending for all the resources and entities. Decrease the number of resources showed on the page.

**Comment by loicsans** [comment]
@martaotto Not sure I understand this issue.
Why remove the pagination?

**Comment by Caroline-Kamau** [comment]
@iperdomo  attached  is the browser trace for the pagination issue. As mentioned , the pagination does not stick on my Firefox browser version 89.0.1 (64-bit)[https://app.zenhub.com/files/326952490/282b4ba0-1429-424c-b255-152de75bbca7/download](https://app.zenhub.com/files/326952490/282b4ba0-1429-424c-b255-152de75bbca7/download)

**Comment by iperdomo** [comment]
@Caroline-Kamau thanks fro commenting. Unfortunately we couldn't see the attached steps of the problem. The `.mht` compressed file contained images that were not visible.

We tried hard to reproduce the problem, and found that is only possible if you have a very low screen resolution: `1024x768` the pagination bar doesn't show properly.

Assuming this numbers as valid, the most common screen resolution are: `1366x768` (HD) or `1920x1080` (Full HD). Combined account for more than 41% of the *population*. The resolution `1024x768` (XGA) is only 2.4%

https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide

A video of the problem:

https://user-images.githubusercontent.com/178474/123284504-96b99280-d50c-11eb-8ecd-ef1e1309d255.mp4

I'm not suggesting the problem is not present. What I'm suggesting is the very few people will face the problem. In the current stats: 9 out of 1556 visitors, use 1024x768.

**Comment by iperdomo** [comment]
After the fix at revision 55da88b

https://user-images.githubusercontent.com/178474/123429510-5408c080-d5c7-11eb-9baf-964f028c4af4.mp4
