### ISSUE TITLE
 Detail page for the entities and individuals is not showing any data

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#346]
After logging user navigates to the full entities page. When entering the detail page you get a blank page. 

It happens in any browser for any entity, e.g. https://digital.gpmarinelitter.org/organisation/337. Looking at the dev tools nothing seems to be sent from the backend. 

https://images.zenhubusercontent.com/326952490/4e177a2e-2d92-4747-9306-501257de9e04/detail_page_issue.mp4

**Comment by GeertSoet** [comment]
In addition, I'm logged in. 
<img width="1439" alt="Screenshot 2021-07-19 at 13 32 58" src="https://user-images.githubusercontent.com/13728925/126153964-8c23f890-fb7e-4a4d-900c-ee5df2f3acf0.png">

**Comment by punchagan** [comment]
Is this screenshot of test? or prod? We'd need to check if your account has been approved, even though you are logged in.

**Comment by GeertSoet** [comment]
It happens both on production as test for me. On test I can edit resources even so my account should be approved.

**Comment by GeertSoet** [comment]
Both pages are functional again, however when editing I am redirected into the even edit page.

**Comment by punchagan** [comment]
Nice catch. I'll fix that.

**Comment by punchagan** [comment]
I'm going to remove the edit button for now, since

1. I don't think admins should be able to stakeholders' information. It is personal information of users, which they are able to edit from their profile. 
2. We don't yet have a form for entities/organizations - they are either created from the data dumps that we import, or from within other forms. We need to create a form for entities to be able to edit them. Let's do this as a separate ticket.

**Comment by GeertSoet** [comment]
Agreed.
