### ISSUE TITLE
Knowledge resource > map > initiative filter not working

### ISSUE THREAD

**Issue by GeertSoet** [akvo/unep-gpml#593]
When selecting the initiative filter, only Norway shows up even though there are plenty of initiatives. 

https://digital.gpmarinelitter.org/browse?country=&transnational=&topic=project%2Caction_plan%2Cpolicy%2Ctechnical_resource%2Cfinancing_resource%2Cevent%2Ctechnology&tag=&q=&offset=0

![Screenshot 2021-11-29 at 11.35.19.png](https://images.zenhubusercontent.com/55d493ca4f7a08fbb7f464b2/123cb312-7058-4f57-acef-cf9c45e2719a)

**Comment by tangrammer** [comment]
@diptigautam just tried to get into the root of this issue/bug and reached that sql https://github.com/akvo/unep-gpml/blob/main/backend/src/gpml/db/landing.sql#L89 
As far as i know, this UI [view](https://github.com/akvo/unep-gpml/blob/main/frontend/src/modules/browse/map-landing.jsx#L6) uses `/landing` BE api 
Surprisingly i discovered that this sql uses a table `project_country` for retrieving geo-initiative/project countries data, I meant surprisingly because i wasn't aware of this table, so very probably this SQL is using a deprecated table, and should be updated to fetch `initiative_geo_coverage table` instead, in the same way as other resources/topic in same query already do
